/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./../components/shared/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('./../components/shared/Tooltip.vue')['default']
    TooltipArrow: typeof import('reka-ui')['TooltipArrow']
    TooltipContent: typeof import('reka-ui')['TooltipContent']
    TooltipPortal: typeof import('reka-ui')['TooltipPortal']
    TooltipProvider: typeof import('reka-ui')['TooltipProvider']
    TooltipRoot: typeof import('reka-ui')['TooltipRoot']
    TooltipTrigger: typeof import('reka-ui')['TooltipTrigger']
  }
}
